# Generated by Django 2.2.7 on 2020-07-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, verbose_name='stud_firstname')),
                ('lname', models.CharField(max_length=100, verbose_name='stud_lastname')),
                ('age', models.IntegerField(verbose_name='stud_age')),
                ('fees', models.FloatField(verbose_name='stud_fees')),
                ('address', models.CharField(max_length=100, verbose_name='stud_address')),
                ('gender', models.CharField(max_length=100, verbose_name='stud_gender')),
            ],
            options={
                'db_table': 'Stud_Info',
            },
        ),
    ]
